- .gitignore
- profefolio/Services/AuthService.cs
- profefolio/appsettings.json
Se agrego una comprobacion para que un administrador de colegio al que no se le haya asignado un colegio no pueda loguearse
> PF-98 Corecciones de permisos de Login

- .gitignore
- TestProfefolio/Auth/AuthTest.cs
- profefolio/Services/AuthService.cs
- profefolio/Services/PersonasService.cs
- profefolio/appsettings.json
Reverts fiuni2023/Profefolio#223
> Revert "Dev"

- TestProfefolio/Profesor/ProfesorTestingPosts.cs
- profefolio/Controllers/ProfesorController.cs
Hice algunas modificaciones en los mensajes de error que se retorna en las excepciones del controlador de Profesor el primero para  la excepcion generica para que muestre un mensaje simple para un error inesperado y el otro cambio en el caso de la excepcion BadHttpRequestException para que mande los dos tipos de errores de manera correcta los cuales son que se repita el email y el nuemro de docuento.
> PF-116 - Backend - Unit test - Profesor - Metodo Post

- TestProfefolio/Profesor/ProfesorTestinPuts.cs
- profefolio/Controllers/ProfesorController.cs
Se modificaron algunas lineas de codigo del controlador para poder guardar la identidad del administrador, entre otras cosas
> PF-117 - Backend - Unit Test - Metodo Put de Profesor

- profefolio/Controllers/ColegioProfesorController.cs
- profefolio/Repository/IColegioProfesor.cs
- profefolio/Services/ColegioProfesorService.cs
Se agregaron filtros extras para poder validar que solo se entregue los datos pertenecientes al usuario que esta soolicitando los datos y que el Id del colegio recibido exista en la tabla de relaciones.
> PF-125 - Correcciones de permisos de los metodos get del controlador de ColegioProfesor

- profefolio/Controllers/ColegioProfesorController.cs
- profefolio/Services/ColegioProfesorService.cs
Primero se deberia aceptar el PR de PF-125 y luego este, porque lo mas seguro es que hayan algunos pequeño conflictos porque se edito el mismo archivo del controlador.
> PF-127 - Correcion de errores encontrados

- profefolio/Controllers/ColegioProfesorController.cs
…icar el id del colegio de la relacion con el id del colegio del admin que queria eliminar
> PF-128 - Correccion de error encontrado en el testeo

- TestProfefolio/Account/AccountGetTest.cs
- profefolio/Controllers/AccountController.cs
- profefolio/Repository/IPersona.cs
Corrección del bug de la paginación negativa
> S3 pf 144 - Back End

- TestProfefolio/Account/AccountDeleteTest.cs
- TestProfefolio/Account/AccountGetTest.cs
- profefolio/Controllers/AccountController.cs
- profefolio/Repository/IPersona.cs
- profefolio/Services/PersonasService.cs
> S3 pf 143 - Back End

- TestProfefolio/Account/AccountDeleteTest.cs
- TestProfefolio/Account/AccountGetTest.cs
- profefolio/Controllers/AccountController.cs
- profefolio/Controllers/ColegiosFullController.cs
- profefolio/Helpers/Mappers/ColegioMapper.cs
- profefolio/Models/DTOs/Colegio/ColegioFullDTO.cs
- profefolio/Repository/IPersona.cs
- profefolio/Services/PersonasService.cs
Agregado el campo de Id del Administrador de Colegio, dentro del colegio
> S3 pf 145 - BackEnd

- profefolio-frontend/src/components/Sidebar.jsx
- profefolio-frontend/src/pages/alumnos/Alumnos.jsx
- profefolio-frontend/src/pages/alumnos/context/StudentContext.jsx
- profefolio-frontend/src/pages/alumnos/helpers/StudentHelper.js
- profefolio-frontend/src/pages/alumnos/styles/Styles.jsx
- profefolio-frontend/src/pages/app/index.jsx
PR para Listar Alumnos, se crearon estilos, la página principal, y los helpers.
> Pf 109 s3 front listar alumnos

- profefolio/Helpers/Mappers/ColegioMapper.cs
Corrección de posible NullReference
> S3 pf 147 - BackEnd

- profefolio/Controllers/ColegioProfesorController.cs
Se soluciono el error de la cantidad de elementos mostrados en la paginacion
> PF-156 - Correccion de paginacion

- TestProfefolio/Profesor/ProfesorTestinPuts.cs
- TestProfefolio/Profesor/ProfesorTestingDeletes.cs
- TestProfefolio/Profesor/ProfesorTestingGets.cs
- TestProfefolio/Profesor/ProfesorTestingPosts.cs
- profefolio/Controllers/ProfesorController.cs
- profefolio/Models/DTOs/ColegioProfesor/ColegioProfesorResultOfCreatedDTO.cs
- profefolio/Models/Entities/Persona.cs
- profefolio/Program.cs
- profefolio/Repository/IProfesor.cs
- profefolio/Services/PersonasService.cs
- profefolio/Services/ProfesorService.cs
Se tiene que poder agregar directamente el profesor creado a la lista de profesores del colegio del administrador, y que el metodo post del controlador de profesores sea accesible solo por el administrador de colegio
> PF-152 - Coreccion de Metodo Post de Profesor

- profefolio/Controllers/MateriaController.cs
- profefolio/Repository/IMateriaLista.cs
- profefolio/Services/MateriaListaService.cs
Solo se permitira que se eliminen las materias que todavia no se esten usando en la tabla materia-clase.
> PF-159 - Correccion del metodo delete del controlador de Clases

- profefolio-frontend/src/pages/colegios/ModalColegios.jsx
Se comentaron las lineas con error
> PF-168 - Corregir codigo de Modal de Colegio

- .gitignore
- profefolio/Services/MateriaListaService.cs
Creado el API para el Find de Materia Lista. Filtra por el Id de materia.
> S3 pf 129 - BackEnd

- profefolio-frontend/src/pages/materias/list/ListDetallesMateria.jsx
> Modificaciones para editar

- profefolio-frontend/src/pages/clases/components/ShowContainer.jsx
- profefolio-frontend/src/pages/clases/components/ShowsStyled.jsx
- profefolio-frontend/src/pages/clases/components/show/AlumnosInscriptos.jsx
- profefolio-frontend/src/pages/clases/components/show/InfoClase.jsx
- profefolio-frontend/src/pages/clases/components/show/MateriasDeClase.jsx
- profefolio-frontend/src/pages/clases/index.jsx
Se me olvido subir el ultimo commit donde solucionaba el error
> Correccion de un error

- profefolio/Controllers/AlumnosController.cs
- profefolio/Controllers/MateriaListasController.cs
- profefolio/Services/AuthService.cs
Reverts fiuni2023/Profefolio#359
> Revert "S4 pf 230 - BackEnd"

- profefolio-frontend/src/components/Paginations.jsx
- profefolio-frontend/src/pages/clases/Helpers/ClassesHelper.js
- profefolio-frontend/src/pages/clases/Helpers/MateriasHelper.js
- profefolio-frontend/src/pages/clases/components/show/MateriasDeClase.jsx
- profefolio-frontend/src/pages/clases/context/ClaseContext.jsx
- profefolio/Controllers/MateriaController.cs
- profefolio/Controllers/ProfesorController.cs
- profefolio/Repository/IMateria.cs
- profefolio/Repository/IProfesor.cs
- profefolio/Services/MateriaService.cs
- profefolio/Services/ProfesorService.cs
PF-159: ya se subio por error con otro ticket en otro PR.
PF-204 Y PF-205: son de frontend
PF-237 Y PF-238: son de backend que tuve que hacer porque los necesitaba en fontend
> PF-159 - PF-204 - PF-205 - PF-237 - PF-238

- profefolio-frontend/src/components/Example Data/ExampleForm.jsx
- profefolio-frontend/src/components/Form.jsx
Fecha: ya permite impedir seleccionar fechas futuras
Contraseña: se mejoro la expresion regular y no permite espacios en blanco 
Correo: se mejoro la expresion regular
> validaciones

- profefolio/Controllers/MateriaController.cs
- profefolio/Services/MateriaService.cs
Se corrigio el error porque antes devolvia hasta las materias asignadas, ahora retorna las materias no asignadas y las materias asignadas pero que estan marcadas como eliminadas.
> PF-247 - Back - Get Materias No Asignadas - Correccion

- profefolio/Services/ColegiosService.cs
Se ordeno descendentemente por el id
> PF-271 - Correccion de get page de colegio

- profefolio-frontend/src/pages/app/index.jsx
- profefolio-frontend/src/pages/home/dashboards/profeHome/index.jsx
- profefolio-frontend/src/pages/profesor-pages/components/ContainerColegios.jsx
- profefolio-frontend/src/pages/profesor-pages/components/Eventos/index.jsx
- profefolio-frontend/src/pages/profesor-pages/components/Horarios/index.jsx
- profefolio-frontend/src/pages/profesor-pages/index.jsx
El PR corresponde a los tickets 265 y 266
> PF-265 y PF-266 

- profefolio/Controllers/AlumnosController.cs
- profefolio/Services/PersonasService.cs
Valida que el alumno no exista previamente en el colegio del administrador
> PF-281 - Validacion de Post de Alumno

- profefolio/Services/PersonasService.cs
> PF-282 se modifica ExistDoc.

- profefolio-frontend/src/pages/clases/context/ClaseContext.jsx
> Correccion de  eslint

- profefolio-frontend/src/components/Card.jsx
- profefolio-frontend/src/context/GeneralContext.jsx
- profefolio-frontend/src/pages/clases/index.jsx
- profefolio/Models/DTOs/Auth/AuthPersonaDTO.cs
- profefolio/Services/AuthService.cs
Se agrego el id del colegio en la respuesta del login del adminsitrador de colegio del lado del backend.
En el frontend agregue el id de colegio recibido al localstorage y agregue un metodo de get para obtenerlo con el GeneralContext.
Tambien en el frontend solucione el error que habia con el grafico en el dashboard de administrador de colegio, el error ocuria cuando se queria mostrar el menu de opciones.
> Add Colegio Id in Token

- profefolio-frontend/src/pages/clases/Helpers/ClassesHelper.js
- profefolio-frontend/src/pages/clases/components/show/MateriasDeClase.jsx
- profefolio-frontend/src/pages/clases/index.jsx
> Pf 211 new

- profefolio/Controllers/EventoController.cs
- profefolio/Helpers/Mappers/EventoMapper.cs
- profefolio/Models/DTOs/Evento/EventoResultFullDTO.cs
- profefolio/Repository/IEvento.cs
- profefolio/Services/EventoService.cs
- profefolio/appsettings.json
Se implementa GetEvento y GetAll para Eventos.
> Pf 286 get evento

- profefolio/Controllers/DashboardProfesorController.cs
- profefolio/Helpers/Mappers/DashboardProfesorMapper.cs
- profefolio/Models/DTOs/DashboardProfesor/GetWithOpcions/DBCardMateriasDTO.cs
- profefolio/Models/DTOs/Materia/MateriaResultFullDTO.cs
- profefolio/Repository/IDashboardProfesor.cs
- profefolio/Repository/IProfesor.cs
- profefolio/Services/DashboardProfesorService.cs
- profefolio/Services/ProfesorService.cs
- profefolio/appsettings.json
Se obtienen las materias de una clase.
> Pf 298 get materias de profesor

- profefolio-frontend/src/pages/clases/Helpers/ClassesHelper.js
- profefolio-frontend/src/pages/clases/components/show/MateriasDeClase.jsx
> Modificaciones en crearMateria/Profesor

- profefolio/Controllers/DocumentoController.cs
- profefolio/Repository/IDocumento.cs
- profefolio/Services/DocumentoService.cs
se implementa el método put para documentos.
> Pf 351 put documentos

- profefolio/Controllers/DocumentoController.cs
- profefolio/Helpers/Mappers/DashboardProfesorMapper.cs
- profefolio/Repository/IDocumento.cs
- profefolio/Services/DocumentoService.cs
Reverts fiuni2023/Profefolio#618
> Revert "Revert "PR-DashboardProfesor-Solucion""

- profefolio/Controllers/DashboardProfesorController.cs
- profefolio/Models/DTOs/DashboardProfesor/GetWithOpcions/DBCardEventosClaseDTO.cs
- profefolio/Models/DTOs/DashboardProfesor/GetWithOpcions/DBCardEventosColegioDTO.cs
- profefolio/Models/DTOs/DashboardProfesor/GetWithOpcions/DBCardEventosMateriaDTO.cs
- profefolio/Repository/IDashboardProfesor.cs
- profefolio/Services/DashboardProfesorService.cs
- profefolio/appsettings.json
Se devuelve todos los eventos de los colegios.
Se devuelve todos los eventos de un colegio.
Se devuelve todos los eventos de una clase.
> Pf 339 eventos adaptar al nuevo modelo

- profefolio/Controllers/ProfesorController.cs
- profefolio/Services/PersonasService.cs
- profefolio/appsettings.json
se cambia EditProfile de PersonasService. Se cambia el metodo put en ProfesoresController.
> Pf 335 put profesor

- profefolio-frontend/src/pages/administrador/components/AdminModal.jsx
- profefolio-frontend/src/pages/alumnos/components/ModalAlumnos.jsx
- profefolio-frontend/src/pages/profesor-pages/pages/documentos/create/CreateModalDocumento.jsx
- profefolio-frontend/src/pages/profesor/components/ModalMensajeProfesor.jsx
- profefolio-frontend/src/pages/profesor/components/ModalProfesor.jsx
- profefolio-frontend/src/pages/profesor/components/style/StyledModalMensaje.jsx
- profefolio-frontend/src/pages/profesor/helpers/ProfeHelper.js
Tambien edite los strings que decian "DIRRECCION"
> Pf 382 manejar profes existentes

- profefolio/Services/MateriaListaService.cs
> S7 pf 308 - backend

- profefolio-frontend/src/pages/clases/components/show/MateriasDeClase.jsx
> Agregue la a al toast
